INSERT INTO FIRST_ENTITY (ID, DESCRIPTION) VALUES (nextval('ENTITY_SEQ'), 'TestDescription1'); --1
INSERT INTO FIRST_ENTITY (ID, DESCRIPTION) VALUES (nextval('ENTITY_SEQ'), 'TestDescription2'); --51

INSERT INTO SECOND_ENTITY (ID, FIRST_ENTITY_ID, NAME) VALUES (nextval('ENTITY_SEQ'), 1, 'TestValue1'); --101
INSERT INTO SECOND_ENTITY (ID, FIRST_ENTITY_ID, NAME) VALUES (nextval('ENTITY_SEQ'), 1, 'TestValue2'); --151
INSERT INTO SECOND_ENTITY (ID, FIRST_ENTITY_ID, NAME) VALUES (nextval('ENTITY_SEQ'), 1, 'TestValue2'); --201
INSERT INTO SECOND_ENTITY (ID, FIRST_ENTITY_ID, NAME) VALUES (nextval('ENTITY_SEQ'), 51, 'TestValue1'); --251
INSERT INTO SECOND_ENTITY (ID, FIRST_ENTITY_ID, NAME) VALUES (nextval('ENTITY_SEQ'), 51, 'TestValue4'); --301

INSERT INTO ADDITIONAL_ATTRIBUTE (SECOND_ENTITY_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (101, 'type', 'Type1');
INSERT INTO ADDITIONAL_ATTRIBUTE (SECOND_ENTITY_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (101, 'color', 'Red');
INSERT INTO ADDITIONAL_ATTRIBUTE (SECOND_ENTITY_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (151, 'color', 'Blue');
INSERT INTO ADDITIONAL_ATTRIBUTE (SECOND_ENTITY_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (201, 'color', 'Blue');
INSERT INTO ADDITIONAL_ATTRIBUTE (SECOND_ENTITY_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (251, 'type', 'Type2');
INSERT INTO ADDITIONAL_ATTRIBUTE (SECOND_ENTITY_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (251, 'color', 'Yellow');
INSERT INTO ADDITIONAL_ATTRIBUTE (SECOND_ENTITY_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (301, 'type', 'Type1');

INSERT INTO ANOTHER_ENTITY (ID, ANIMAL, CITY, IS_OBSOLETE) VALUES (nextval('ENTITY_SEQ'), 'Duck', 'Warsaw', true); --351
INSERT INTO ANOTHER_ENTITY (ID, ANIMAL, CITY, IS_OBSOLETE) VALUES (nextval('ENTITY_SEQ'), 'Goat', 'Warsaw', null); --401
INSERT INTO ANOTHER_ENTITY (ID, ANIMAL, CITY, IS_OBSOLETE) VALUES (nextval('ENTITY_SEQ'), 'Cat', 'Kiev', true); --451
INSERT INTO ANOTHER_ENTITY (ID, ANIMAL, CITY, IS_OBSOLETE) VALUES (nextval('ENTITY_SEQ'), 'Dolphin', 'Chicago', false); --501
INSERT INTO ANOTHER_ENTITY (ID, ANIMAL, CITY, IS_OBSOLETE) VALUES (nextval('ENTITY_SEQ'), 'Dog', 'Paris', null); --551
INSERT INTO ANOTHER_ENTITY (ID, ANIMAL, CITY, IS_OBSOLETE) VALUES (nextval('ENTITY_SEQ'), 'Donkey', 'Berlin', null); --601